#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ALLOWED_UNWIRED_ERC = {
    "pin_not_connected",
    "pin_not_driven",
    "power_pin_not_driven",
}

FORBIDDEN_ERC = {
    "endpoint_off_grid",
    "lib_symbol_mismatch",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate a generated placement-only KiCad schematic for reusable BOM workflows."
    )
    parser.add_argument("schematic", type=Path, help="Path to the generated .kicad_sch file.")
    parser.add_argument("--erc", type=Path, help="Optional KiCad ERC report generated by kicad-cli sch erc.")
    parser.add_argument("--svg", type=Path, help="Optional SVG generated by kicad-cli sch export svg.")
    parser.add_argument(
        "--allow-extends",
        action="store_true",
        help="Allow embedded lib_symbols that use KiCad (extends ...) aliases.",
    )
    return parser.parse_args()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(errors="replace")


def check_schematic(path: Path, allow_extends: bool) -> list[str]:
    errors: list[str] = []
    text = read_text(path)

    used_lib_ids = set(re.findall(r'\(lib_id\s+"([^"]+)"\)', text))
    embedded_lib_ids = set(re.findall(r'(?m)^\t+\(symbol\s+"([^"]+:[^"]+)"', text))

    if not used_lib_ids:
        errors.append("No placed symbols with lib_id were found.")

    if re.search(r"(?m)^\t\(lib_symbols\)\s*$", text):
        errors.append("The schematic has an empty (lib_symbols) section; KiCad will render red ?? placeholders.")

    missing = sorted(used_lib_ids - embedded_lib_ids)
    if missing:
        errors.append(
            "Missing embedded lib_symbols for used lib_id values: " + ", ".join(missing[:20])
        )

    if "Device:D_Fast" in text:
        errors.append("Device:D_Fast was found, but this is not a stable KiCad generic symbol. Use Device:D or a verified symbol.")

    if not allow_extends and re.search(r'\(extends\s+"[^"]+"\)', text):
        errors.append(
            "Embedded lib_symbols contain (extends ...) aliases. Prefer concrete base symbols for generated placement schematics."
        )

    return errors


def check_erc(path: Path) -> list[str]:
    errors: list[str] = []
    text = read_text(path)
    codes = re.findall(r"(?m)^\[([^]]+)\]", text)

    forbidden = sorted(code for code in set(codes) if code in FORBIDDEN_ERC)
    if forbidden:
        errors.append("Forbidden ERC issue types found: " + ", ".join(forbidden))

    unexpected = sorted(code for code in set(codes) if code not in ALLOWED_UNWIRED_ERC and code not in FORBIDDEN_ERC)
    if unexpected:
        errors.append(
            "Unexpected ERC issue types found for an unwired placement schematic: " + ", ".join(unexpected)
        )

    missing_words = re.findall(
        r"(?i)(symbol not found|library not found|not found|missing|ライブラリ|見つかりません|見つからない)",
        text,
    )
    if missing_words:
        errors.append("ERC report contains missing symbol/library wording.")

    return errors


def check_svg(path: Path) -> list[str]:
    errors: list[str] = []
    text = read_text(path)
    if re.search(r"<desc>\s*\?\?\s*</desc>|>\s*\?\?\s*</text>", text):
        errors.append("SVG export contains visible ?? placeholders.")
    return errors


def main() -> int:
    args = parse_args()
    errors: list[str] = []

    if not args.schematic.is_file():
        errors.append(f"Schematic not found: {args.schematic}")
    else:
        errors.extend(check_schematic(args.schematic, args.allow_extends))

    if args.erc:
        if args.erc.is_file():
            errors.extend(check_erc(args.erc))
        else:
            errors.append(f"ERC report not found: {args.erc}")

    if args.svg:
        if args.svg.is_file():
            errors.extend(check_svg(args.svg))
        else:
            errors.append(f"SVG export not found: {args.svg}")

    if errors:
        print("KiCad placement validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("KiCad placement validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
